# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default=' ', max_length=1000, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
