# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Content'),
        ),
    ]
