# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160526_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.TextField(max_length=100)),
                ('owner_type', models.CharField(choices=[('0', 'Builder'), ('1', 'Agent'), ('2', 'Owner')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('property_type', models.CharField(choices=[('00', 'Apartment'), ('01', 'Villament'), ('02', 'Individual House'), ('03', 'Raw House'), ('04', 'Villa'), ('05', 'Plot'), ('06', 'Builder Floor')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contact_start_time', models.TimeField()),
                ('contact_end_time', models.TimeField()),
                ('property_condition', models.BooleanField()),
                ('city', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('block', models.TextField(max_length=100)),
                ('house_no', models.TextField(max_length=100)),
                ('project_name', models.TextField(max_length=100)),
                ('buildup_area', models.PositiveIntegerField()),
                ('carpat_area', models.PositiveIntegerField(max_length=100)),
                ('no_of_bedroom', models.PositiveIntegerField()),
                ('no_of_bathroom', models.PositiveIntegerField()),
                ('no_of_balconies', models.PositiveIntegerField()),
                ('property_value', models.IntegerField()),
                ('property_rent', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField()),
                ('maintenance_charges', models.PositiveIntegerField()),
                ('bachelors_allowed', models.BooleanField()),
                ('non_veg_allowed', models.BooleanField(max_length=100)),
                ('pets_allowed', models.BooleanField()),
                ('registration_fee_included', models.NullBooleanField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('possession_date', models.DateField()),
                ('year_of_construction', models.PositiveIntegerField()),
                ('property_status', models.TextField(choices=[('1', 'Free Hold'), ('2', 'CPOA')], max_length=100)),
                ('total_floors', models.PositiveIntegerField()),
                ('floor_no', models.PositiveIntegerField()),
                ('property_facing', models.CharField(choices=[('0', 'West'), ('1', 'East'), ('3', 'South')], max_length=1)),
                ('separate_dining_space', models.BooleanField()),
                ('servant_room', models.BooleanField()),
                ('furnishing_type', models.CharField(choices=[('0', 'SEMI'), ('2', 'FULL')], max_length=1)),
                ('amenities', models.TextField(max_length=100)),
                ('listing_status', models.CharField(choices=[('0', 'Active'), ('1', 'InActive'), ('2', 'Pending')], max_length=1)),
                ('property_for', models.CharField(choices=[('0', 'Sale'), ('1', 'RENT')], max_length=1)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
