# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='block',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpat_area',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('1', 'Free Hold'), ('2', 'CPOA')], max_length=100),
        ),
    ]
