# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180913_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='createOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
