# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180915_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(max_length=254, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
