# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180915_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='', verbose_name='data_file')),
                ('name', models.CharField(max_length=100, verbose_name='file_name')),
            ],
        ),
    ]
