# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_binarystorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarystorage',
            name='data_binary',
            field=models.BinaryField(null=True, verbose_name='file_binary'),
        ),
    ]
